class Types {
  static REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';

  static REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';

  static REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE';

  static ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';

  static ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

  static ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

  static AUTH_REQUEST = 'AUTH_REQUEST';

  static AUTH_SUCCESS = 'AUTH_SUCCESS';

  static AUTH_FAILURE = 'AUTH_FAILURE';

  static FETCH_REQUEST = 'FETCH_REQUEST';

  static FETCH_SUCCESS = 'FETCH_SUCCESS';

  static FETCH_FAILURE = 'FETCH_FAILURE';
}

export default Types;
